### ISSUE TITLE
TaskA

### ISSUE THREAD

**Issue by assrichiacoli** [assrichiacoli/hw#13]
half-done because:
1. It works weirdly! when I run it
In [127]: runfile('/Users/tatanavolkova/Desktop/питон/taskA.py', wdir='/Users/tatanavolkova/Desktop/питон')

/Users/tatanavolkova/Desktop/питон$ ls

and input a command there, it outputs some error

FileSystemError: /Users/tatanavolkova/Desktop/питон already exists (for example)

but then when I put the command here
In [128]: ls
it works just fine

2. `head` `tail` `touch` `find` output syntax error when I type the command
touch pop
  File "<ipython-input-128-553d89a437a5>", line 1
    touch pop
            ^
SyntaxError: invalid syntax (for example)

I can't understand why and also can't test them because of this :(

**Comment by YakutovDmitriy** [comment]
Actually I have `IndentationError` right now when I try to execute it

**Comment by assrichiacoli** [comment]
where exactly?

**Comment by YakutovDmitriy** [comment]
I guess we discussed this yesterday

**Comment by assrichiacoli** [comment]
done (also grep, cp, mv, rm)

**Comment by YakutovDmitriy** [comment]
* `cd`. You write some cases like `cmdargs[0] == '.'`. Why? You can just use join. Also `cd .` means that user wants to change directory to current one (in other works change nothing). Also path can be more complex like `cd ../a/b/c/../d`. Actual implementation of `cd` is simpler, there are no cases, just join old path and new path
* `touch`. You forgot to close the file :)
* `mv` and `cp`. You can improve them. In actual `mv` and `cp` the second argument can be directory. In this case file moves (copies in `cp` case) into this directory with the same name
